const Skills = () => {
    console.log("Utelias mieli vai? Täältä löydät pienen koosteen osaamisestani.")
    console.group("Osaamiseni:");
    console.groupCollapsed("Kehittäminen");
    console.log("Java, Python, JavaScript");
    console.log("Yli 20 vuoden kokemus");
    console.log("Selkeät ratkaisut, ei turhaa monimutkaisuutta");
    console.groupEnd();
    console.groupCollapsed("Arkkitehtuuri");
    console.log("Sovellusarkkitehtuuri");
    console.log("Integraatiot");
    console.log("Pilvi-infra");
    console.log("ADR-käytännöt");
    console.groupEnd();
    console.groupCollapsed("Data ja tekoäly");
    console.log("Microsoft Fabric");
    console.log("Medaljoniarkkitehtuuri");
    console.log("MCP, A2A, Azure AI Foundry");
    console.log("GDPR-vaatimustenmukaisuus");
    console.groupEnd();
    console.groupCollapsed("Vaatimustenmukaisuus ja tietoturva");
    console.log("ISO 27001 ISMS");
    console.log("GDPR, NIS2");
    console.log("EU AI Act");
    console.groupEnd();
    console.groupCollapsed("Johtaminen");
    console.log("Tuotekehityksen johtaminen");
    console.log("Teknologiastrategia");
    console.log("Johtoryhmätyöskentely");
    console.log("Tiimit: muutamasta yli 40 henkilöön");
    console.groupEnd();
    console.groupEnd();
    console.group("Yhteystiedot:");
    console.log("info@petrituomaala.fi");
    console.groupEnd();
    console.group("Sivun koodit:");
    console.log("https://github.com/ptuomaal/petrituomaala");
    console.groupEnd();
}
export default Skills;
