const Skills = () => {
    console.log("Utelias mieli vai? Täältä löydät pienen koosteen osaamisestani.")
    console.group("Osaamiseni:");
    console.groupCollapsed("Yleiset");
    console.log("Tiimien ja funktioiden vetäminen");
    console.log("Pehmeät taidot ja kommunikointi");
    console.log("Tuotekehitysprosessit");
    console.log("Tuotekehitystyökalut ja lisenssit");
    console.log("Saan asiat tehtyä");
    console.groupEnd();
    console.groupCollapsed("Koodaus");
    console.group("Erinomaiset taidot");
    console.log("Java");
    console.log("Java EE / Jakarta EE");
    console.log("Spring");
    console.groupEnd();
    console.groupCollapsed("Hyvät taidot");
    console.log("JavaScript");
    console.log("HTML");
    console.log("CSS");
    console.log("Python");
    console.groupEnd();
    console.groupCollapsed("Itsenäiseen työhön pystyn");
    console.log("C/C++");
    console.log("Qt");
    console.log("Mobiilikehitys");
    console.groupEnd();
    console.groupEnd();
    console.groupCollapsed("Data");
    console.group("Erinomaiset taidot");
    console.log("Datan esikäsittely");
    console.log("Datan analysointi");
    console.groupEnd();
    console.groupCollapsed("Hyvät taidot");
    console.log("Python");
    console.groupEnd();
    console.groupCollapsed("Itsenäiseen työhön pystyn");
    console.log("Datan visualsointi");
    console.log("Kafka");
    console.log("Spark");
    console.log("Tensorflow");
    console.log("Scikit-learn");
    console.log("Matpotlib");
    console.log("Seaborn");
    console.groupEnd();
    console.groupEnd();
    console.groupCollapsed("Ympäristöt");
    console.group("Erinomaiset taidot");
    console.log("Wildfly");
    console.groupEnd();
    console.groupCollapsed("Hyvät taidot");
    console.log("Keycloak");
    console.log("Jenkins / CI / CD");
    console.log("Skriptaus");
    console.groupEnd();
    console.groupCollapsed("Itsenäiseen työhön pystyn");
    console.log("Pilvi");
    console.log("Docker");
    console.log("Palvelimet");
    console.log("Tietokannat");
    console.groupEnd();
    console.groupEnd();
    console.groupEnd();
    console.group("Yhteystiedot:");
    console.log("petri.tuomaala@gmail.com");
    console.groupEnd();
}
export default Skills;
